In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
df = pd.read_excel('demo_mining_accidents.xlsx', header = 0, index_col = "Acc_ID")

In [ ]:
df.head(50)

,On Site Incident,Off Site Incident,On Site Nearmiss,Off Site Nearmiss,Fatal HI/PI,Lost Workday Case (LWC) HI/PI,Restricted Work Case (RWC) HI/PI,Medical Treatment Case (MTC) HI/PI,First Aid Case (FAC) HI/PI,Age Factor,Skill Level Factor
Acc_ID,,,,,,,,,,,
1,1.0,0.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,41,Unskilled
2,1.0,0.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,36,Semi Skilled
3,1.0,0.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,26,Skilled
4,1.0,0.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,31,Skilled
5,1.0,0.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,28,Unskilled
6,1.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,27,Unskilled
7,1.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,23,Semi Skilled
8,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,25,Semi Skilled
9,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,30,Semi Skilled
10,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,26,Unskilled
11,0.0,0.0,13.0,1.0,0.0,0.0,0.0,0.0,0.0,32,Semi Skilled
12,0.0,0.0,13.0,1.0,0.0,0.0,0.0,0.0,0.0,45,Skilled
13,1.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,28,Unskilled
14,0.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,31,Unskilled
15,2.0,0.0,10.0,5.0,0.0,0.0,0.0,0.0,0.0,47,Skilled
16,2.0,0.0,10.0,5.0,0.0,0.0,0.0,0.0,0.0,32,Skilled
17,2.0,0.0,10.0,5.0,0.0,0.0,0.0,0.0,0.0,37,Unskilled
18,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,58,Skilled
19,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,37,Skilled
20,2.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,28,Unskilled
21,2.0,0.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,26,Semi Skilled
22,0.0,0.0,28.0,4.0,0.0,0.0,0.0,0.0,0.0,29,Semi Skilled
23,0.0,0.0,28.0,4.0,0.0,0.0,0.0,0.0,0.0,38,Skilled
24,0.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,54,Skilled
25,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,43,Semi Skilled
26,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,58,Skilled
27,1.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,50,Unskilled
28,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,44,Skilled
29,1.0,0.0,11.0,3.0,0.0,0.0,0.0,0.0,0.0,42,Skilled
30,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,59,Unskilled
31,0.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,38,Semi Skilled
32,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,47,Unskilled
33,1.0,0.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,54,Skilled
34,1.0,0.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,55,Skilled
35,1.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,45,Skilled
36,1.0,0.0,14.0,4.0,0.0,0.0,0.0,0.0,0.0,40,Skilled
37,1.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,32,Unskilled
38,1.0,0.0,11.0,1.0,0.0,0.0,0.0,0.0,0.0,52,Unskilled
39,0.0,0.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,47,Skilled
40,2.0,0.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,37,Skilled
41,1.0,0.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,58,Skilled
42,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,41,Semi Skilled
43,1.0,2.0,18.0,1.0,0.0,0.0,0.0,0.0,0.0,44,Unskilled
44,1.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,39,Semi Skilled
45,2.0,0.0,21.0,3.0,0.0,0.0,0.0,0.0,0.0,54,Semi Skilled
46,1.0,0.0,22.0,1.0,0.0,0.0,0.0,0.0,0.0,57,Skilled
47,0.0,0.0,19.0,1.0,0.0,0.0,0.0,0.0,0.0,41,Skilled
48,1.0,0.0,14.0,2.0,0.0,0.0,0.0,0.0,0.0,43,Skilled
49,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,42,Semi Skilled
50,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,44,Skilled

In [ ]:
list(enumerate(df.columns))

[(0, 'On Site Incident'),
 (1, 'Off Site Incident'),
 (2, 'On Site Nearmiss'),
 (3, 'Off Site Nearmiss'),
 (4, 'Fatal HI/PI'),
 (5, 'Lost Workday Case (LWC) HI/PI'),
 (6, 'Restricted Work Case (RWC) HI/PI'),
 (7, 'Medical Treatment Case (MTC) HI/PI'),
 (8, 'First Aid Case (FAC) HI/PI'),
 (9, 'Age Factor'),
 (10, 'Skill Level Factor')]

In [ ]:
df.shape
df.isnull().sum()

On Site Incident                      1
Off Site Incident                     1
On Site Nearmiss                      1
Off Site Nearmiss                     1
Fatal HI/PI                           1
Lost Workday Case (LWC) HI/PI         1
Restricted Work Case (RWC) HI/PI      1
Medical Treatment Case (MTC) HI/PI    1
First Aid Case (FAC) HI/PI            1
Age Factor                            0
Skill Level Factor                    0
dtype: int64

In [ ]:
df["Skill Level Factor"].describe()

count         446
unique          3
top       Skilled
freq          235
Name: Skill Level Factor, dtype: object

In [ ]:
df["Skill Level Factor"].value_counts(normalize=True) * 100

Skill Level Factor
Skilled         52.690583
Semi Skilled    34.977578
Unskilled       12.331839
Name: proportion, dtype: float64

In [ ]:
onsite_list = df["On Site Incident"].value_counts()
onsite_list

On Site Incident
0.0    235
1.0    124
2.0     52
3.0     16
6.0      7
4.0      6
8.0      3
5.0      2
Name: count, dtype: int64

In [ ]:
df.iloc[:, 0:10].mean(axis = 0)

On Site Incident                       0.844944
Off Site Incident                      0.056180
On Site Nearmiss                       7.600000
Off Site Nearmiss                      0.604494
Fatal HI/PI                            0.020225
Lost Workday Case (LWC) HI/PI          0.015730
Restricted Work Case (RWC) HI/PI       0.031461
Medical Treatment Case (MTC) HI/PI     0.031461
First Aid Case (FAC) HI/PI             0.137079
Age Factor                            43.123318
dtype: float64